# version: '2.4.1'

services:
  wso2:
    image: wso2/wso2am:4.1.0-alpine
    ports:
      - '8280:8280'
      - '8243:8243'
      - '9443:9443'
    container_name: wso2
  node-app:
    image: tobecci/express:1.0.0
    ports:
      - '5000:5000'
    container_name: node-app